# Local verification build only. Same as Dockerfile but skips the go-licenses
# regeneration step (internal/licenses/third-party.txt is already committed),
# which needs a template excluded from the build context. Build with
# --network=host so Go module downloads work in this environment.
FROM golang:alpine AS builder

ARG VERSION=dev-local

COPY . /app
WORKDIR /app

RUN apk upgrade && apk add git npm && \
    npm ci && npm run package && \
    CGO_ENABLED=0 go build -ldflags "-s -w -X github.com/axllent/mailpit/config.Version=${VERSION}" -o /mailpit

FROM alpine:latest
COPY --from=builder /mailpit /mailpit
RUN apk upgrade --no-cache && apk add --no-cache tzdata
EXPOSE 1025/tcp 1110/tcp 8025/tcp
HEALTHCHECK --interval=15s --start-period=10s --start-interval=1s CMD ["/mailpit", "readyz"]
ENTRYPOINT ["/mailpit"]
